pipelines:
  branches:
    v0.11.3:
      - step:
          name: Run tests and build
          image: node:18.12.1
          caches:
            - node
          script:
            - npm install
            - npm test
            - npm run build-storybook
          artifacts:
            - storybook-static/**
      - step:
          name: Deploy build on remote server
          deployment: staging
          script:
            - pipe: atlassian/rsync-deploy:0.8.1
              variables:
                USER: $SSH_USER
                SERVER: $SSH_HOST
                REMOTE_PATH: $SSH_PATH
                LOCAL_PATH: 'storybook-static'
                EXTRA_ARGS: '-rzv --delete --quiet'
